[package]
name = "nparty"
version = "0.0.2"
authors = ["Alex Jago <4475543+alexjago@users.noreply.github.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "N-Party-Preferred distribution of Australian Senate ballots and subsequent analysis."
default-run = "nparty"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.3"
serde = "1.0.105"
serde_derive = "1.0.105"
serde_json = "1.0"
regex = "1"
unicode-segmentation = "1.6.0"
ansi_term = "0.12.1"
maplit = "1.0.2"
atty = "0.2.14"
lazy_static = "1.4.0"
itertools = "0.9.0"
counter = "0.4.3"
zip = "0.5.5"
zip-extensions = "0.4.0"
factorial = "0.2.0"
clap = {version = "3", features = ["color", "derive", "suggestions"]}
toml_edit = {version = "0.12.3", features = ["serde"]}
tabwriter = "1.2.1"
ron = "0.5.1"
url = "2.1.1"
reqwest = {version = "0.10.4", features = ["blocking", "gzip", "brotli"]}
glob = "0.3.0"
enum-utils = "0.1.2"
Inflector = "0.11.4"
anyhow = "1"
klask = "1"

[profile.release]
debug = true

[[bin]]
name = "nparty"
path = "src/main.rs"

[[bin]]
name = "nparty-gui"
path = "src/gui.rs"
